import type { Client, Contact, Task, StaffMember, WorkspaceMember } from "@/lib/types"
import { emptyStaffDetails } from "@/lib/types"

const clientIds = {
  sarah: "dummy-client-001",
  james: "dummy-client-002",
  mei: "dummy-client-003",
  liam: "dummy-client-004",
  priya: "dummy-client-005",
  ben: "dummy-client-006",
  olivia: "dummy-client-007",
  daniel: "dummy-client-008",
}

export const dummyClients: Client[] = [
  {
    id: clientIds.sarah,
    name: "Sarah Thompson",
    displayName: "Sarah Thompson",
    iconColor: "#6366f1",
    iconText: "ST",
    iconShape: "circle",
    participant: {
      firstName: "Sarah",
      middleName: "Jane",
      lastName: "Thompson",
      preferredName: "Sarah",
      dateOfBirth: "1995-03-14",
      gender: "Female",
      pronouns: "She/Her",
      ethnicity: "Australian",
      language: "English",
      primaryDiagnosis: "Cerebral Palsy",
      secondaryDiagnosis: "Anxiety Disorder",
      address: "12 Banksia St, Carlton VIC 3053",
      email: "sarah.thompson@email.com",
      mobile: "0412 345 678",
      phone: "",
      preferredContactMethod: "Mobile",
      preferredSignMethod: "Email",
      ndisNumber: "431 234 567",
      medicareNumber: "2345 67890 1",
      centrelinkNumber: "123 456 789A",
      externalId: "EXT-001",
      serviceCommencementDate: "2024-01-15",
      serviceExitDate: "",
      checkInPeriod: "",
      checkInStartDate: "",
      fundingType: "plan-managed",
      planManagerName: "Rebecca Torres",
      planManagerEmail: "rebecca@myplanmanager.com.au",
      planManagerOrg: "My Plan Manager",
      planStartDate: "2025-07-01",
      planEndDate: "2026-06-30",
    },
    industry: ["NDIS"],
    lastInteraction: "2026-03-15",
    revenue: "$48,200",
    headcount: "",
    lastFunding: "2025-07-01",
    website: "",
    owner: "Emma Richards",
    assignedTo: null,
    summary: "Active participant with support coordination and therapy services.",
    about: "Sarah is a 30-year-old participant who lives independently in a supported apartment. She requires assistance with daily living, physiotherapy, and community access.",
    status: "active",
  },
  {
    id: clientIds.james,
    name: "James Wilson",
    displayName: "James Wilson",
    iconColor: "#f59e0b",
    iconText: "JW",
    iconShape: "circle",
    participant: {
      firstName: "James",
      middleName: "",
      lastName: "Wilson",
      preferredName: "Jimmy",
      dateOfBirth: "1988-11-22",
      gender: "Male",
      pronouns: "He/Him",
      ethnicity: "Australian",
      language: "English",
      primaryDiagnosis: "Autism Spectrum Disorder",
      secondaryDiagnosis: "",
      address: "67 Hawthorn Rd, Caulfield VIC 3162",
      email: "james.wilson@email.com",
      mobile: "0423 456 789",
      phone: "07 3456 7890",
      preferredContactMethod: "Phone",
      preferredSignMethod: "In Person",
      ndisNumber: "431 345 678",
      medicareNumber: "3456 78901 2",
      centrelinkNumber: "234 567 890B",
      externalId: "EXT-002",
      serviceCommencementDate: "2023-06-01",
      serviceExitDate: "",
      checkInPeriod: "",
      checkInStartDate: "",
      fundingType: "plan-managed",
      planManagerName: "David Nguyen",
      planManagerEmail: "david@planpartners.com.au",
      planManagerOrg: "Plan Partners",
      planStartDate: "2025-06-01",
      planEndDate: "2026-05-31",
    },
    industry: ["NDIS"],
    lastInteraction: "2026-03-14",
    revenue: "$62,500",
    headcount: "",
    lastFunding: "2025-06-01",
    website: "",
    owner: "Sam Lee",
    assignedTo: null,
    summary: "Long-term participant with SIL and community participation.",
    about: "James lives in a Supported Independent Living arrangement with two other housemates. He works part-time at a local cafe with support and enjoys art classes on weekends.",
    status: "active",
  },
  {
    id: clientIds.mei,
    name: "Mei Chen",
    displayName: "Mei Chen",
    iconColor: "#10b981",
    iconText: "MC",
    iconShape: "circle",
    participant: {
      firstName: "Mei",
      middleName: "",
      lastName: "Chen",
      preferredName: "Mei",
      dateOfBirth: "2001-07-03",
      gender: "Female",
      pronouns: "She/Her",
      ethnicity: "Chinese-Australian",
      language: "English, Mandarin",
      primaryDiagnosis: "Intellectual Disability",
      secondaryDiagnosis: "Epilepsy",
      address: "8 Marlow Ave, Glen Iris VIC 3146",
      email: "mei.chen@email.com",
      mobile: "0434 567 890",
      phone: "",
      preferredContactMethod: "Mobile",
      preferredSignMethod: "Email",
      ndisNumber: "431 456 789",
      medicareNumber: "4567 89012 3",
      centrelinkNumber: "345 678 901C",
      externalId: "EXT-003",
      serviceCommencementDate: "2024-03-10",
      serviceExitDate: "",
      checkInPeriod: "",
      checkInStartDate: "",
      fundingType: "ndia-managed",
      planManagerName: "",
      planManagerEmail: "",
      planManagerOrg: "",
      planStartDate: "2025-09-01",
      planEndDate: "2026-08-31",
    },
    industry: ["NDIS"],
    lastInteraction: "2026-03-12",
    revenue: "$35,800",
    headcount: "",
    lastFunding: "2025-09-01",
    website: "",
    owner: "Emma Richards",
    assignedTo: null,
    summary: "Young participant transitioning from school to adult services.",
    about: "Mei recently finished school and is exploring supported employment and further education options. She needs an interpreter for complex discussions with her family.",
    status: "active",
  },
  {
    id: clientIds.liam,
    name: "Liam O'Brien",
    displayName: "Liam O'Brien",
    iconColor: "#ef4444",
    iconText: "LO",
    iconShape: "circle",
    participant: {
      firstName: "Liam",
      middleName: "Patrick",
      lastName: "O'Brien",
      preferredName: "Liam",
      dateOfBirth: "1975-09-28",
      gender: "Male",
      pronouns: "He/Him",
      ethnicity: "Irish-Australian",
      language: "English",
      primaryDiagnosis: "Acquired Brain Injury",
      secondaryDiagnosis: "Depression",
      address: "45 Rosewood Cres, Northcote VIC 3070",
      email: "",
      mobile: "0445 678 901",
      phone: "07 5678 9012",
      preferredContactMethod: "Phone",
      preferredSignMethod: "In Person",
      ndisNumber: "431 567 890",
      medicareNumber: "5678 90123 4",
      centrelinkNumber: "456 789 012D",
      externalId: "EXT-004",
      serviceCommencementDate: "2022-11-01",
      serviceExitDate: "",
      checkInPeriod: "",
      checkInStartDate: "",
      fundingType: "plan-managed",
      planManagerName: "Lisa Crawford",
      planManagerEmail: "lisa@firstchoicepm.com.au",
      planManagerOrg: "First Choice Plan Management",
      planStartDate: "2025-11-01",
      planEndDate: "2026-10-31",
    },
    industry: ["NDIS"],
    lastInteraction: "2026-03-10",
    revenue: "$78,400",
    headcount: "",
    lastFunding: "2025-11-01",
    website: "",
    owner: "Sam Lee",
    assignedTo: null,
    summary: "Complex needs participant with high-intensity support.",
    about: "Liam sustained an ABI in a car accident 12 years ago. He requires 24/7 support and uses a wheelchair. His plan includes SIL, therapy, and assistive technology.",
    status: "active",
  },
  {
    id: clientIds.priya,
    name: "Priya Sharma",
    displayName: "Priya Sharma",
    iconColor: "#8b5cf6",
    iconText: "PS",
    iconShape: "circle",
    participant: {
      firstName: "Priya",
      middleName: "",
      lastName: "Sharma",
      preferredName: "Priya",
      dateOfBirth: "1999-01-17",
      gender: "Female",
      pronouns: "She/Her",
      ethnicity: "Indian-Australian",
      language: "English, Hindi",
      primaryDiagnosis: "Down Syndrome",
      secondaryDiagnosis: "",
      address: "19 Cedar St, Brunswick VIC 3056",
      email: "priya.sharma@email.com",
      mobile: "0456 789 012",
      phone: "",
      preferredContactMethod: "Email",
      preferredSignMethod: "Email",
      ndisNumber: "431 678 901",
      medicareNumber: "6789 01234 5",
      centrelinkNumber: "567 890 123E",
      externalId: "EXT-005",
      serviceCommencementDate: "2024-08-01",
      serviceExitDate: "",
      checkInPeriod: "",
      checkInStartDate: "",
      fundingType: "self-managed",
      planManagerName: "",
      planManagerEmail: "",
      planManagerOrg: "",
      planStartDate: "2025-08-01",
      planEndDate: "2026-07-31",
    },
    industry: ["NDIS"],
    lastInteraction: "2026-03-16",
    revenue: "$41,000",
    headcount: "",
    lastFunding: "2025-08-01",
    website: "",
    owner: "Emma Richards",
    assignedTo: null,
    summary: "Participant focused on supported employment and social skills.",
    about: "Priya is passionate about cooking and dreams of working in a commercial kitchen. She attends social skills groups twice a week and has a supported employment placement.",
    status: "active",
  },
  {
    id: clientIds.ben,
    name: "Ben Nguyen",
    displayName: "Ben Nguyen",
    iconColor: "#0ea5e9",
    iconText: "BN",
    iconShape: "circle",
    participant: {
      firstName: "Ben",
      middleName: "Thanh",
      lastName: "Nguyen",
      preferredName: "Ben",
      dateOfBirth: "2010-05-20",
      gender: "Male",
      pronouns: "He/Him",
      ethnicity: "Vietnamese-Australian",
      language: "English, Vietnamese",
      primaryDiagnosis: "Autism Spectrum Disorder",
      secondaryDiagnosis: "ADHD",
      address: "21 Foster Rd, Footscray VIC 3011",
      email: "",
      mobile: "",
      phone: "07 6789 0123",
      preferredContactMethod: "Phone",
      preferredSignMethod: "Email",
      ndisNumber: "431 789 012",
      medicareNumber: "7890 12345 6",
      centrelinkNumber: "678 901 234F",
      externalId: "EXT-006",
      serviceCommencementDate: "2023-02-15",
      serviceExitDate: "",
      checkInPeriod: "",
      checkInStartDate: "",
      fundingType: "plan-managed",
      planManagerName: "Rebecca Torres",
      planManagerEmail: "rebecca@myplanmanager.com.au",
      planManagerOrg: "My Plan Manager",
      planStartDate: "2025-02-15",
      planEndDate: "2026-02-14",
    },
    industry: ["NDIS"],
    lastInteraction: "2026-03-13",
    revenue: "$52,600",
    headcount: "",
    lastFunding: "2025-02-15",
    website: "",
    owner: "Sam Lee",
    assignedTo: null,
    summary: "Child participant with early intervention and therapy services.",
    about: "Ben is a school-aged participant who receives OT, speech therapy, and behavioural support. His parents are actively involved in his therapy program.",
    status: "active",
  },
  {
    id: clientIds.olivia,
    name: "Olivia Martin",
    displayName: "Olivia Martin",
    iconColor: "#ec4899",
    iconText: "OM",
    iconShape: "circle",
    participant: {
      firstName: "Olivia",
      middleName: "Grace",
      lastName: "Martin",
      preferredName: "Liv",
      dateOfBirth: "1992-12-05",
      gender: "Female",
      pronouns: "She/Her",
      ethnicity: "Australian",
      language: "English",
      primaryDiagnosis: "Multiple Sclerosis",
      secondaryDiagnosis: "",
      address: "5 Maple Way, Coburg VIC 3058",
      email: "olivia.martin@email.com",
      mobile: "0467 890 123",
      phone: "",
      preferredContactMethod: "Email",
      preferredSignMethod: "Email",
      ndisNumber: "431 890 123",
      medicareNumber: "8901 23456 7",
      centrelinkNumber: "789 012 345G",
      externalId: "EXT-007",
      serviceCommencementDate: "2025-01-10",
      serviceExitDate: "",
      checkInPeriod: "",
      checkInStartDate: "",
      fundingType: "plan-managed",
      planManagerName: "David Nguyen",
      planManagerEmail: "david@planpartners.com.au",
      planManagerOrg: "Plan Partners",
      planStartDate: "2026-01-10",
      planEndDate: "2027-01-09",
    },
    industry: ["NDIS"],
    lastInteraction: "2026-03-11",
    revenue: "$29,300",
    headcount: "",
    lastFunding: "2026-01-10",
    website: "",
    owner: "Emma Richards",
    assignedTo: null,
    summary: "New participant adjusting to progressive condition management.",
    about: "Olivia was recently diagnosed with MS and is in the early stages of building her support team. She works from home as a graphic designer and needs assistance with fatigue management and home modifications.",
    status: "active",
  },
  {
    id: clientIds.daniel,
    name: "Daniel Cooper",
    displayName: "Daniel Cooper",
    iconColor: "#f97316",
    iconText: "DC",
    iconShape: "circle",
    participant: {
      firstName: "Daniel",
      middleName: "",
      lastName: "Cooper",
      preferredName: "Dan",
      dateOfBirth: "1982-04-11",
      gender: "Male",
      pronouns: "He/Him",
      ethnicity: "Aboriginal Australian",
      language: "English",
      primaryDiagnosis: "Spinal Cord Injury",
      secondaryDiagnosis: "Chronic Pain",
      address: "3 Lily Ct, Preston VIC 3072",
      email: "dan.cooper@email.com",
      mobile: "0478 901 234",
      phone: "",
      preferredContactMethod: "Mobile",
      preferredSignMethod: "In Person",
      ndisNumber: "431 901 234",
      medicareNumber: "9012 34567 8",
      centrelinkNumber: "890 123 456H",
      externalId: "EXT-008",
      serviceCommencementDate: "2021-05-20",
      serviceExitDate: "",
      checkInPeriod: "",
      checkInStartDate: "",
      fundingType: "ndia-managed",
      planManagerName: "",
      planManagerEmail: "",
      planManagerOrg: "",
      planStartDate: "2025-05-20",
      planEndDate: "2026-05-19",
    },
    industry: ["NDIS"],
    lastInteraction: "2026-03-16",
    revenue: "$91,200",
    headcount: "",
    lastFunding: "2025-05-20",
    website: "",
    owner: "Sam Lee",
    assignedTo: null,
    summary: "Long-term participant with assistive technology and home mod needs.",
    about: "Daniel is a wheelchair user with a T6 spinal cord injury. He is very active in adaptive sports and advocates for accessibility in his local community. His plan includes SIL, AT, and vehicle modifications.",
    status: "active",
  },
]

export const dummyContacts: Contact[] = [
  { id: "dummy-contact-001", clientId: clientIds.sarah, clientName: "Sarah Thompson", name: "Dr. Rachel Green", relationship: "general-practitioner", email: "r.green@medicalpractice.com.au", phone: "07 3456 0001" },
  { id: "dummy-contact-002", clientId: clientIds.sarah, clientName: "Sarah Thompson", name: "Linda Thompson", relationship: "next-of-kin", email: "linda.thompson@email.com", phone: "0412 000 001" },
  { id: "dummy-contact-003", clientId: clientIds.sarah, clientName: "Sarah Thompson", name: "Mark Stevens", relationship: "physiotherapist", email: "m.stevens@physio.com.au", phone: "07 3456 0002" },
  { id: "dummy-contact-004", clientId: clientIds.james, clientName: "James Wilson", name: "Karen Mitchell", relationship: "support-coordinator", email: "k.mitchell@supportcoord.com.au", phone: "0423 000 001" },
  { id: "dummy-contact-005", clientId: clientIds.james, clientName: "James Wilson", name: "Robert Wilson", relationship: "next-of-kin", email: "rob.wilson@email.com", phone: "0423 000 002" },
  { id: "dummy-contact-006", clientId: clientIds.james, clientName: "James Wilson", name: "Harmony House SIL", relationship: "sil-provider", email: "intake@harmonyhouse.com.au", phone: "07 3456 0003" },
  { id: "dummy-contact-007", clientId: clientIds.mei, clientName: "Mei Chen", name: "Dr. Helen Park", relationship: "general-practitioner", email: "h.park@clinic.com.au", phone: "07 3456 0004" },
  { id: "dummy-contact-008", clientId: clientIds.mei, clientName: "Mei Chen", name: "Wei Chen", relationship: "next-of-kin", email: "wei.chen@email.com", phone: "0434 000 001" },
  { id: "dummy-contact-009", clientId: clientIds.liam, clientName: "Liam O'Brien", name: "OPG Queensland", relationship: "decision-maker-opg", email: "enquiries@opg.qld.gov.au", phone: "1300 653 187" },
  { id: "dummy-contact-010", clientId: clientIds.liam, clientName: "Liam O'Brien", name: "Dr. Fiona Blake", relationship: "mental-health", email: "f.blake@psychology.com.au", phone: "07 3456 0005" },
  { id: "dummy-contact-011", clientId: clientIds.priya, clientName: "Priya Sharma", name: "Anita Sharma", relationship: "next-of-kin", email: "anita.sharma@email.com", phone: "0456 000 001" },
  { id: "dummy-contact-012", clientId: clientIds.ben, clientName: "Ben Nguyen", name: "Linh Nguyen", relationship: "next-of-kin", email: "linh.nguyen@email.com", phone: "0489 000 001" },
  { id: "dummy-contact-013", clientId: clientIds.ben, clientName: "Ben Nguyen", name: "Dr. Amy Foster", relationship: "general-practitioner", email: "a.foster@kidsclinic.com.au", phone: "07 3456 0006" },
  { id: "dummy-contact-014", clientId: clientIds.olivia, clientName: "Olivia Martin", name: "Dr. Nathan Cross", relationship: "general-practitioner", email: "n.cross@medcentre.com.au", phone: "07 3456 0007" },
  { id: "dummy-contact-015", clientId: clientIds.daniel, clientName: "Daniel Cooper", name: "Public Trustee QLD", relationship: "public-trustee", email: "info@pt.qld.gov.au", phone: "1300 360 044" },
  { id: "dummy-contact-016", clientId: clientIds.daniel, clientName: "Daniel Cooper", name: "Sunrise CAS", relationship: "cas-provider", email: "referrals@sunrisecas.com.au", phone: "07 3456 0008" },
]

export const dummyStaff: StaffMember[] = [
  {
    id: "dummy-staff-001",
    name: "Emma Richards",
    iconText: "ER",
    status: "active",
    invitedEmail: "emma.richards@coordination.com.au",
    details: {
      ...emptyStaffDetails,
      firstName: "Emma", lastName: "Richards", preferredName: "Emma",
      dateOfBirth: "1990-06-15", gender: "Female", pronouns: "She/Her",
      address: "14 Station St, Fitzroy VIC 3065",
      email: "emma.richards@coordination.com.au", mobile: "0400 111 001", phone: "",
      role: "Senior Support Coordinator", department: "Support Coordination",
      employmentType: "Full-time", startDate: "2022-03-01", endDate: "",
      qualifications: "Bachelor of Social Work, Cert IV Disability",
      certifications: "First Aid, NDIS Worker Screening, Mental Health First Aid",
      emergencyContactName: "Tom Richards", emergencyContactPhone: "0400 111 002",
      notes: "",
    },
  },
  {
    id: "dummy-staff-002",
    name: "Sam Lee",
    iconText: "SL",
    status: "active",
    invitedEmail: "sam.lee@coordination.com.au",
    details: {
      ...emptyStaffDetails,
      firstName: "Sam", lastName: "Lee", preferredName: "Sam",
      dateOfBirth: "1987-02-20", gender: "Male", pronouns: "He/Him",
      address: "92 Albert Rd, Richmond VIC 3121",
      email: "sam.lee@coordination.com.au", mobile: "0400 222 001", phone: "",
      role: "Support Coordinator", department: "Support Coordination",
      employmentType: "Full-time", startDate: "2023-01-15", endDate: "",
      qualifications: "Bachelor of Community Services",
      certifications: "First Aid, NDIS Worker Screening",
      emergencyContactName: "Jenny Lee", emergencyContactPhone: "0400 222 002",
      notes: "",
    },
  },
  {
    id: "dummy-staff-003",
    name: "Tara Patel",
    iconText: "TP",
    status: "active",
    invitedEmail: "tara.patel@coordination.com.au",
    details: {
      ...emptyStaffDetails,
      firstName: "Tara", lastName: "Patel", preferredName: "Tara",
      dateOfBirth: "1993-09-10", gender: "Female", pronouns: "She/Her",
      address: "7 Grove Rd, Hawthorn VIC 3122",
      email: "tara.patel@coordination.com.au", mobile: "0400 333 001", phone: "",
      role: "Specialist Support Coordinator", department: "Support Coordination",
      employmentType: "Full-time", startDate: "2023-07-01", endDate: "",
      qualifications: "Master of Occupational Therapy",
      certifications: "First Aid, NDIS Worker Screening, Positive Behaviour Support",
      emergencyContactName: "Raj Patel", emergencyContactPhone: "0400 333 002",
      notes: "Specialises in complex/high-intensity participants.",
    },
  },
  {
    id: "dummy-staff-004",
    name: "Jake Morrison",
    iconText: "JM",
    status: "active",
    invitedEmail: "jake.morrison@coordination.com.au",
    details: {
      ...emptyStaffDetails,
      firstName: "Jake", lastName: "Morrison", preferredName: "Jake",
      dateOfBirth: "1996-12-01", gender: "Male", pronouns: "He/Him",
      address: "33 Park Ave, Brunswick East VIC 3057",
      email: "jake.morrison@coordination.com.au", mobile: "0400 444 001", phone: "",
      role: "Support Worker", department: "Direct Support",
      employmentType: "Part-time", startDate: "2024-06-01", endDate: "",
      qualifications: "Cert III Individual Support",
      certifications: "First Aid, NDIS Worker Screening, Manual Handling",
      emergencyContactName: "Sue Morrison", emergencyContactPhone: "0400 444 002",
      notes: "",
    },
  },
  {
    id: "dummy-staff-005",
    name: "Amy Tran",
    iconText: "AT",
    status: "invited",
    invitedEmail: "amy.tran@coordination.com.au",
    details: {
      ...emptyStaffDetails,
      firstName: "Amy", lastName: "Tran", preferredName: "Amy",
      dateOfBirth: "1998-04-25", gender: "Female", pronouns: "She/Her",
      address: "28 River St, Abbotsford VIC 3067",
      email: "amy.tran@coordination.com.au", mobile: "0400 555 001", phone: "",
      role: "Admin & Intake Officer", department: "Administration",
      employmentType: "Full-time", startDate: "2026-04-01", endDate: "",
      qualifications: "Bachelor of Business Administration",
      certifications: "NDIS Worker Screening",
      emergencyContactName: "Minh Tran", emergencyContactPhone: "0400 555 002",
      notes: "Starting next month.",
    },
  },
]

const today = new Date()
const fmt = (d: Date) => d.toISOString().split("T")[0]
const daysFromNow = (n: number) => { const d = new Date(today); d.setDate(d.getDate() + n); return fmt(d) }

export const dummyTasks: Task[] = [
  {
    id: "dummy-task-001", title: "Plan review meeting - Sarah Thompson", description: "Prepare for Sarah's annual plan review. Collate progress reports from OT and physio, update goal tracking sheet.",
    status: "in-progress", assignee: "Emma Richards", client: "Sarah Thompson", clientId: clientIds.sarah,
    dueDate: daysFromNow(3), attachments: [], chargeType: "07_002_0106_8_3", timeSpent: 45,
    secondaryChargeType: "", secondaryTimeSpent: 0,
  },
  {
    id: "dummy-task-002", title: "SIL provider quarterly report - James Wilson", description: "Request and review quarterly report from Harmony House. Confirm incident logs and support hours align with plan.",
    status: "todo", assignee: "Sam Lee", client: "James Wilson", clientId: clientIds.james,
    dueDate: daysFromNow(7), attachments: [], chargeType: "07_002_0106_8_3", timeSpent: 0,
    secondaryChargeType: "", secondaryTimeSpent: 0,
  },
  {
    id: "dummy-task-003", title: "School-to-work transition plan - Mei Chen", description: "Coordinate with Mei's school, family, and employment provider to finalise her transition plan.",
    status: "in-progress", assignee: "Emma Richards", client: "Mei Chen", clientId: clientIds.mei,
    dueDate: daysFromNow(5), attachments: [], chargeType: "07_004_0132_8_3", timeSpent: 90,
    secondaryChargeType: "", secondaryTimeSpent: 0,
  },
  {
    id: "dummy-task-004", title: "AT assessment follow-up - Daniel Cooper", description: "Follow up with OT on the power wheelchair assessment. Check delivery timeline and trial availability.",
    status: "todo", assignee: "Sam Lee", client: "Daniel Cooper", clientId: clientIds.daniel,
    dueDate: daysFromNow(2), attachments: [], chargeType: "07_002_0106_8_3", timeSpent: 0,
    secondaryChargeType: "", secondaryTimeSpent: 0,
  },
  {
    id: "dummy-task-005", title: "New participant intake - Olivia Martin", description: "Complete service agreement, upload signed documents, and schedule initial meeting.",
    status: "done", assignee: "Emma Richards", client: "Olivia Martin", clientId: clientIds.olivia,
    dueDate: daysFromNow(-5), attachments: [], chargeType: "07_001_0106_8_3", timeSpent: 120,
    secondaryChargeType: "", secondaryTimeSpent: 0,
  },
  {
    id: "dummy-task-006", title: "Behaviour support plan review - Ben Nguyen", description: "Meet with Ben's behavioural therapist to review PBS. Update family on strategies for home.",
    status: "todo", assignee: "Tara Patel", client: "Ben Nguyen", clientId: clientIds.ben,
    dueDate: daysFromNow(10), attachments: [], chargeType: "07_004_0132_8_3", timeSpent: 0,
    secondaryChargeType: "", secondaryTimeSpent: 0,
  },
  {
    id: "dummy-task-007", title: "Epilepsy management plan update - Mei Chen", description: "Liaise with Dr. Park re: updated seizure protocol. Ensure SIL staff and school are trained.",
    status: "todo", assignee: "Tara Patel", client: "Mei Chen", clientId: clientIds.mei,
    dueDate: daysFromNow(14), attachments: [], chargeType: "", timeSpent: 0,
    secondaryChargeType: "", secondaryTimeSpent: 0,
  },
  {
    id: "dummy-task-008", title: "Supported employment review - Priya Sharma", description: "Check in with Priya's DES provider on job coaching hours and kitchen placement progress.",
    status: "in-progress", assignee: "Emma Richards", client: "Priya Sharma", clientId: clientIds.priya,
    dueDate: daysFromNow(1), attachments: [], chargeType: "07_002_0106_8_3", timeSpent: 30,
    secondaryChargeType: "", secondaryTimeSpent: 0,
  },
  {
    id: "dummy-task-009", title: "OPG consent for service change - Liam O'Brien", description: "Submit consent request to OPG for adding community nursing to Liam's plan.",
    status: "todo", assignee: "Sam Lee", client: "Liam O'Brien", clientId: clientIds.liam,
    dueDate: daysFromNow(4), attachments: [], chargeType: "07_002_0106_8_3", timeSpent: 0,
    secondaryChargeType: "", secondaryTimeSpent: 0,
  },
  {
    id: "dummy-task-010", title: "Home modification quote - Daniel Cooper", description: "Obtain two quotes for bathroom modifications. Coordinate with OT for recommendation letter.",
    status: "in-progress", assignee: "Sam Lee", client: "Daniel Cooper", clientId: clientIds.daniel,
    dueDate: daysFromNow(8), attachments: [], chargeType: "07_002_0106_8_3", timeSpent: 60,
    secondaryChargeType: "", secondaryTimeSpent: 0,
  },
  {
    id: "dummy-task-011", title: "Plan utilisation report - All participants", description: "Run monthly budget utilisation report for all active participants. Flag any under/over-utilised plans.",
    status: "todo", assignee: "Emma Richards", client: "", clientId: null,
    dueDate: daysFromNow(6), attachments: [], chargeType: "", timeSpent: 0,
    secondaryChargeType: "", secondaryTimeSpent: 0,
  },
  {
    id: "dummy-task-012", title: "Vehicle modification claim - Daniel Cooper", description: "Submit NDIS claim for approved vehicle modifications. Attach OT report and invoice.",
    status: "done", assignee: "Sam Lee", client: "Daniel Cooper", clientId: clientIds.daniel,
    dueDate: daysFromNow(-3), attachments: [], chargeType: "07_799_0132_8_3", timeSpent: 45,
    secondaryChargeType: "", secondaryTimeSpent: 0,
  },
  {
    id: "dummy-task-013", title: "Respite booking confirmation - James Wilson", description: "Confirm 2-night respite stay at Sunflower House for the Easter break. Send details to family.",
    status: "todo", assignee: "Tara Patel", client: "James Wilson", clientId: clientIds.james,
    dueDate: daysFromNow(0), attachments: [], chargeType: "07_002_0106_8_3", timeSpent: 0,
    secondaryChargeType: "", secondaryTimeSpent: 0,
  },
  {
    id: "dummy-task-014", title: "Transport provider quote - Priya Sharma", description: "Get quotes from two accessible transport providers for Priya's weekly trips to day program.",
    status: "todo", assignee: "Sam Lee", client: "Priya Sharma", clientId: clientIds.priya,
    dueDate: daysFromNow(1), attachments: [], chargeType: "07_002_0106_8_3", timeSpent: 0,
    secondaryChargeType: "", secondaryTimeSpent: 0,
  },
  {
    id: "dummy-task-015", title: "Incident report follow-up - Ben Nguyen", description: "Follow up on incident report from SIL provider. Schedule meeting with family and behaviour therapist.",
    status: "in-progress", assignee: "Emma Richards", client: "Ben Nguyen", clientId: clientIds.ben,
    dueDate: daysFromNow(0), attachments: [], chargeType: "07_004_0132_8_3", timeSpent: 25,
    secondaryChargeType: "", secondaryTimeSpent: 0,
  },
  {
    id: "dummy-task-016", title: "NDIS plan reassessment prep - Liam O'Brien", description: "Compile evidence and reports for Liam's upcoming plan reassessment. Book planning meeting with LAC.",
    status: "todo", assignee: "Tara Patel", client: "Liam O'Brien", clientId: clientIds.liam,
    dueDate: daysFromNow(12), attachments: [], chargeType: "07_002_0106_8_3", timeSpent: 0,
    secondaryChargeType: "", secondaryTimeSpent: 0,
  },
  {
    id: "dummy-task-017", title: "Allied health progress notes - Sarah Thompson", description: "Chase up OT and speech pathologist for quarterly progress notes. Update CRM with received reports.",
    status: "done", assignee: "Sam Lee", client: "Sarah Thompson", clientId: clientIds.sarah,
    dueDate: daysFromNow(-7), attachments: [], chargeType: "07_002_0106_8_3", timeSpent: 35,
    secondaryChargeType: "", secondaryTimeSpent: 0,
  },
  {
    id: "dummy-task-018", title: "Service agreement renewal - Mei Chen", description: "Mei's service agreement expires next month. Draft renewal and schedule signing meeting with family.",
    status: "todo", assignee: "Emma Richards", client: "Mei Chen", clientId: clientIds.mei,
    dueDate: daysFromNow(9), attachments: [], chargeType: "07_001_0106_8_3", timeSpent: 0,
    secondaryChargeType: "", secondaryTimeSpent: 0,
  },
  {
    id: "dummy-task-019", title: "Community access risk assessment - Daniel Cooper", description: "Complete risk assessment for Daniel's new community access activities. Submit to plan manager.",
    status: "done", assignee: "Tara Patel", client: "Daniel Cooper", clientId: clientIds.daniel,
    dueDate: daysFromNow(-2), attachments: [], chargeType: "07_002_0106_8_3", timeSpent: 55,
    secondaryChargeType: "", secondaryTimeSpent: 0,
  },
  {
    id: "dummy-task-020", title: "Medication chart update - James Wilson", description: "Liaise with GP to update James's medication chart after recent specialist appointment.",
    status: "in-progress", assignee: "Sam Lee", client: "James Wilson", clientId: clientIds.james,
    dueDate: daysFromNow(0), attachments: [], chargeType: "", timeSpent: 15,
    secondaryChargeType: "", secondaryTimeSpent: 0,
  },
]

export const dummyMembers: WorkspaceMember[] = [
  {
    id: "dummy-member-001", workspace_id: "dummy-ws", user_id: "dummy-user-001",
    role: "super-admin", status: "active", invited_email: null, team: null, created_at: "2022-03-01T00:00:00Z",
    name: "Emma Richards", email: "emma.richards@coordination.com.au",
  },
  {
    id: "dummy-member-002", workspace_id: "dummy-ws", user_id: "dummy-user-002",
    role: "admin", status: "active", invited_email: null, team: null, created_at: "2023-01-15T00:00:00Z",
    name: "Sam Lee", email: "sam.lee@coordination.com.au",
  },
  {
    id: "dummy-member-003", workspace_id: "dummy-ws", user_id: "dummy-user-003",
    role: "coordinator", status: "active", invited_email: null, team: "Brisbane", created_at: "2023-07-01T00:00:00Z",
    name: "Tara Patel", email: "tara.patel@coordination.com.au",
  },
  {
    id: "dummy-member-004", workspace_id: "dummy-ws", user_id: "dummy-user-004",
    role: "coordinator", status: "active", invited_email: null, team: "Gold Coast", created_at: "2024-06-01T00:00:00Z",
    name: "Jake Morrison", email: "jake.morrison@coordination.com.au",
  },
  {
    id: "dummy-member-005", workspace_id: "dummy-ws", user_id: null,
    role: "coordinator", status: "invited", invited_email: "amy.tran@coordination.com.au", team: "Brisbane", created_at: "2026-03-10T00:00:00Z",
    name: "amy.tran@coordination.com.au", email: "amy.tran@coordination.com.au",
  },
]
