[project]
id = ""

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/auth/callback"]

[auth.email]
enable_signup = true
enable_confirmations = false

[auth.email.template.confirmation]
subject = "Confirm your email address"
content_path = "./supabase/templates/confirmation.html"
