"use client"

import { useEffect, useMemo, useRef, useState } from "react"
import { ChevronDown, RotateCcw, X } from "lucide-react"
import { DeleteActionsMenu } from "@/components/delete-actions-menu"
import { FixedDatePickerDropdown } from "@/components/fixed-date-picker-dropdown"
import { FixedSelectDropdown } from "@/components/fixed-select-dropdown"
import type { BudgetReleasePeriod, ParticipantDetails } from "@/lib/types"
import type { FundingReleaseCadence, NdisFundingComponent } from "@/lib/ndis-funding-pools"
import {
  FUNDING_RELEASE_CADENCE_OPTIONS,
  NDIS_FUNDING_COMPONENTS,
  NDIS_FUNDING_COMPONENT_LABELS,
} from "@/lib/ndis-funding-pools"
import {
  generateReleasePeriods,
  getReleaseScheduleWarning,
  sumReleasePeriodAmounts,
} from "@/lib/budget-utils"
import { formatNumberDisplay, formatNumberInput, parseFormattedNumber } from "@/lib/number-input"

interface BudgetSidebarFormProps {
  isEditing: boolean
  p: ParticipantDetails
  budgetName: string
  fundingComponent: NdisFundingComponent | ""
  allocatedAmount: string
  releaseCadence: FundingReleaseCadence
  budgetStartDate: string
  budgetEndDate: string
  releasePeriods: BudgetReleasePeriod[]
  budgetStartPickerOpen: boolean
  budgetEndPickerOpen: boolean
  isComponentDropdownOpen: boolean
  isCadenceDropdownOpen: boolean
  onSetBudgetName: (name: string) => void
  onSetFundingComponent: (component: NdisFundingComponent) => void
  onSetAllocatedAmount: (amount: string) => void
  onSetReleaseCadence: (cadence: FundingReleaseCadence) => void
  onSetBudgetStartDate: (date: string) => void
  onSetBudgetEndDate: (date: string) => void
  onSetReleasePeriods: (periods: BudgetReleasePeriod[]) => void
  onSetBudgetStartPickerOpen: (open: boolean) => void
  onSetBudgetEndPickerOpen: (open: boolean) => void
  onSetIsComponentDropdownOpen: (open: boolean) => void
  onSetIsCadenceDropdownOpen: (open: boolean) => void
  onUsePlanDates: () => void
  onSave: () => void
  onClose: () => void
  onDelete?: (id: string) => void
  editingBudgetId: string | null
}

function formatPickerDate(dateStr: string) {
  if (!dateStr) return null
  return new Date(`${dateStr}T00:00:00`).toLocaleDateString("en-AU", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
  })
}

function formatCurrency(value: number) {
  return `$${value.toLocaleString("en-AU", { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`
}

type BudgetDateSource = "custom" | "ndis_plan"

function resolveBudgetDateSource(
  startDate: string,
  endDate: string,
  ndisPlanStartDate?: string,
  ndisPlanEndDate?: string
): BudgetDateSource {
  if (
    ndisPlanStartDate &&
    ndisPlanEndDate &&
    startDate === ndisPlanStartDate &&
    endDate === ndisPlanEndDate
  ) {
    return "ndis_plan"
  }

  return "custom"
}

export function BudgetSidebarForm({
  isEditing,
  p,
  budgetName,
  fundingComponent,
  allocatedAmount,
  releaseCadence,
  budgetStartDate,
  budgetEndDate,
  releasePeriods,
  budgetStartPickerOpen,
  budgetEndPickerOpen,
  isComponentDropdownOpen,
  isCadenceDropdownOpen,
  onSetBudgetName,
  onSetFundingComponent,
  onSetAllocatedAmount,
  onSetReleaseCadence,
  onSetBudgetStartDate,
  onSetBudgetEndDate,
  onSetReleasePeriods,
  onSetBudgetStartPickerOpen,
  onSetBudgetEndPickerOpen,
  onSetIsComponentDropdownOpen,
  onSetIsCadenceDropdownOpen,
  onUsePlanDates,
  onSave,
  onClose,
  onDelete,
  editingBudgetId,
}: BudgetSidebarFormProps) {
  const selectedComponent = NDIS_FUNDING_COMPONENTS.find((c) => c.id === fundingComponent)
  const cadenceOption = FUNDING_RELEASE_CADENCE_OPTIONS.find((opt) => opt.value === releaseCadence)
  const parsedAmount = parseFormattedNumber(allocatedAmount)

  const autoGeneratedPeriods = useMemo(() => {
    if (!budgetStartDate || !budgetEndDate || parsedAmount <= 0) return []
    return generateReleasePeriods(budgetStartDate, budgetEndDate, releaseCadence, parsedAmount)
  }, [budgetStartDate, budgetEndDate, releaseCadence, parsedAmount])

  const scheduleKey = `${budgetStartDate}|${budgetEndDate}|${releaseCadence}|${parsedAmount}`
  const prevScheduleKeyRef = useRef(scheduleKey)
  const componentDropdownRef = useRef<HTMLButtonElement>(null)
  const cadenceDropdownRef = useRef<HTMLButtonElement>(null)
  const dateSourceDropdownRef = useRef<HTMLButtonElement>(null)
  const startDateRef = useRef<HTMLButtonElement>(null)
  const endDateRef = useRef<HTMLButtonElement>(null)
  const [dateSource, setDateSource] = useState<BudgetDateSource>("custom")
  const [isDateSourceDropdownOpen, setIsDateSourceDropdownOpen] = useState(false)

  const hasNdisPlanDates = Boolean(p.planStartDate && p.planEndDate)

  useEffect(() => {
    if (autoGeneratedPeriods.length === 0) {
      if (releasePeriods.length > 0) onSetReleasePeriods([])
      return
    }
    if (prevScheduleKeyRef.current === scheduleKey) return
    prevScheduleKeyRef.current = scheduleKey
    onSetReleasePeriods(autoGeneratedPeriods)
  }, [scheduleKey, autoGeneratedPeriods, releasePeriods.length, onSetReleasePeriods])

  const applyGeneratedSchedule = () => {
    if (autoGeneratedPeriods.length > 0) onSetReleasePeriods(autoGeneratedPeriods)
  }

  const scheduleWarning = getReleaseScheduleWarning(parsedAmount, releasePeriods)
  const periodsTotal = sumReleasePeriodAmounts(releasePeriods)

  const canSave =
    Boolean(budgetName.trim()) &&
    Boolean(budgetStartDate) &&
    Boolean(budgetEndDate) &&
    Boolean(fundingComponent) &&
    parsedAmount > 0 &&
    releasePeriods.length > 0

  const handleResetSchedule = () => {
    applyGeneratedSchedule()
  }

  const handlePeriodAmountChange = (periodId: string, value: string) => {
    const amount = parseFormattedNumber(value)
    onSetReleasePeriods(
      releasePeriods.map((period) =>
        period.id === periodId ? { ...period, allocatedAmount: amount } : period
      )
    )
  }

  const dateSourceOptions: { value: BudgetDateSource; label: string; description?: string }[] = [
    { value: "custom", label: "Custom dates" },
    ...(hasNdisPlanDates
      ? [{
          value: "ndis_plan" as const,
          label: "Same as NDIS plan",
          description: `${formatPickerDate(p.planStartDate)} – ${formatPickerDate(p.planEndDate)}`,
        }]
      : []),
  ]

  const activeDateSourceLabel =
    dateSourceOptions.find((option) => option.value === dateSource)?.label ?? "Custom dates"

  useEffect(() => {
    setDateSource(resolveBudgetDateSource(budgetStartDate, budgetEndDate, p.planStartDate, p.planEndDate))
  }, [budgetStartDate, budgetEndDate, p.planStartDate, p.planEndDate])

  const handleDateSourceChange = (source: BudgetDateSource) => {
    setDateSource(source)
    setIsDateSourceDropdownOpen(false)
    if (source === "ndis_plan") onUsePlanDates()
  }

  const handleManualStartDateChange = (value: string) => {
    setDateSource("custom")
    onSetBudgetStartDate(value)
    onSetBudgetStartPickerOpen(false)
  }

  const handleManualEndDateChange = (value: string) => {
    setDateSource("custom")
    onSetBudgetEndDate(value)
    onSetBudgetEndPickerOpen(false)
  }

  return (
    <>
      <div className="flex items-center justify-between px-[24px] pb-[4px] pt-[20px]">
        <h2 className="text-[13px] font-semibold text-folk-text">
          {isEditing ? "Edit budget" : "New budget"}
        </h2>
        <button
          type="button"
          onClick={onClose}
          className="flex h-[24px] w-[24px] items-center justify-center rounded-none text-folk-secondary transition-colors hover:bg-folk-hover hover:text-folk-text"
          tabIndex={0}
          aria-label="Close budget form"
        >
          <X className="h-[14px] w-[14px]" strokeWidth={1.5} />
        </button>
      </div>

      <div className="min-h-0 flex-1 overflow-y-auto">
        <div className="space-y-[14px] px-[24px] py-[14px]">
          <div>
            <label className="mb-[4px] block text-[12px] font-medium text-folk-secondary">Budget name *</label>
            <input
              type="text"
              value={budgetName}
              onChange={(e) => onSetBudgetName(e.target.value)}
              className="h-[36px] w-full rounded-none border border-folk-border bg-folk-page px-[12px] text-[13px] font-medium text-folk-text outline-none hover:border-[#ccc] focus:border-[#a3c4f3]"
            />
          </div>

          <div>
            <label className="mb-[4px] block text-[12px] font-medium text-folk-secondary">Funding component *</label>
            <div className="relative">
              <button
                ref={componentDropdownRef}
                type="button"
                onClick={() => {
                  onSetIsComponentDropdownOpen(!isComponentDropdownOpen)
                  onSetIsCadenceDropdownOpen(false)
                }}
                className="flex h-[36px] w-full items-center rounded-none border border-folk-border bg-folk-page px-[12px] text-[13px] font-medium text-folk-text transition-colors hover:border-[#ccc]"
                tabIndex={0}
              >
                <span className="min-w-0 flex-1 truncate text-left">
                  {selectedComponent ? selectedComponent.label : "Select funding component"}
                </span>
                <ChevronDown
                  className={`ml-[8px] h-[14px] w-[14px] shrink-0 text-folk-secondary transition-transform ${isComponentDropdownOpen ? "rotate-180" : ""}`}
                  strokeWidth={1.5}
                />
              </button>
              <FixedSelectDropdown
                isOpen={isComponentDropdownOpen}
                anchorRef={componentDropdownRef}
                onClose={() => onSetIsComponentDropdownOpen(false)}
                estimatedHeight={NDIS_FUNDING_COMPONENTS.length * 52 + 8}
                minWidth={280}
              >
                {NDIS_FUNDING_COMPONENTS.map((component) => {
                  const isSelected = fundingComponent === component.id
                  return (
                    <button
                      key={component.id}
                      type="button"
                      onClick={() => {
                        onSetFundingComponent(component.id)
                        onSetIsComponentDropdownOpen(false)
                      }}
                      className={`flex w-full flex-col items-start px-[12px] py-[8px] text-left transition-colors hover:bg-folk-hover ${isSelected ? "bg-[var(--folk-border-subtle)]" : ""}`}
                      tabIndex={0}
                    >
                      <span className="text-[12px] font-medium text-folk-text">{component.label}</span>
                      <span className="mt-[2px] text-[11px] text-folk-secondary">{component.description}</span>
                    </button>
                  )
                })}
              </FixedSelectDropdown>
            </div>
            {selectedComponent && (
              <p className="mt-[6px] text-[11px] text-folk-secondary">{selectedComponent.description}</p>
            )}
          </div>

          <div>
            <label className="mb-[4px] block text-[12px] font-medium text-folk-secondary">Plan allocation *</label>
            <div className="relative">
              <span className="pointer-events-none absolute left-[12px] top-1/2 -translate-y-1/2 text-[13px] font-medium text-folk-secondary">$</span>
              <input
                type="text"
                inputMode="decimal"
                value={allocatedAmount}
                onChange={(e) => onSetAllocatedAmount(formatNumberInput(e.target.value))}
                className="h-[36px] w-full rounded-none border border-folk-border bg-folk-page pl-[24px] pr-[12px] text-[13px] font-medium text-folk-text outline-none hover:border-[#ccc] focus:border-[#a3c4f3]"
              />
            </div>
          </div>

          <div>
            <label className="mb-[4px] block text-[12px] font-medium text-folk-secondary">Funding release schedule *</label>
            <div className="relative">
              <button
                ref={cadenceDropdownRef}
                type="button"
                onClick={() => {
                  onSetIsCadenceDropdownOpen(!isCadenceDropdownOpen)
                  onSetIsComponentDropdownOpen(false)
                }}
                className="flex h-[36px] w-full items-center rounded-none border border-folk-border bg-folk-page px-[12px] text-[13px] font-medium text-folk-text transition-colors hover:border-[#ccc]"
                tabIndex={0}
              >
                <span className="min-w-0 flex-1 truncate text-left">
                  {cadenceOption?.label || "Select release schedule"}
                </span>
                <ChevronDown
                  className={`ml-[8px] h-[14px] w-[14px] shrink-0 text-folk-secondary transition-transform ${isCadenceDropdownOpen ? "rotate-180" : ""}`}
                  strokeWidth={1.5}
                />
              </button>
              <FixedSelectDropdown
                isOpen={isCadenceDropdownOpen}
                anchorRef={cadenceDropdownRef}
                onClose={() => onSetIsCadenceDropdownOpen(false)}
                estimatedHeight={FUNDING_RELEASE_CADENCE_OPTIONS.length * 52 + 8}
                minWidth={280}
              >
                {FUNDING_RELEASE_CADENCE_OPTIONS.map((opt) => (
                  <button
                    key={opt.value}
                    type="button"
                    onClick={() => {
                      onSetReleaseCadence(opt.value)
                      onSetIsCadenceDropdownOpen(false)
                    }}
                    className={`flex w-full flex-col items-start px-[12px] py-[8px] text-left transition-colors hover:bg-folk-hover ${releaseCadence === opt.value ? "bg-[var(--folk-border-subtle)]" : ""}`}
                    tabIndex={0}
                  >
                    <span className="text-[12px] font-medium text-folk-text">{opt.label}</span>
                    <span className="mt-[2px] text-[11px] text-folk-secondary">{opt.description}</span>
                  </button>
                ))}
              </FixedSelectDropdown>
            </div>
          </div>

          {dateSourceOptions.length > 1 && (
            <div>
              <label className="mb-[4px] block text-[12px] font-medium text-folk-secondary">Date range</label>
              <div className="relative">
                <button
                  ref={dateSourceDropdownRef}
                  type="button"
                  onClick={() => {
                    setIsDateSourceDropdownOpen(!isDateSourceDropdownOpen)
                    onSetIsComponentDropdownOpen(false)
                    onSetIsCadenceDropdownOpen(false)
                  }}
                  className="flex h-[36px] w-full items-center rounded-none border border-folk-border bg-folk-page px-[12px] text-[13px] font-medium text-folk-text transition-colors hover:border-[#ccc]"
                  tabIndex={0}
                >
                  <span className="min-w-0 flex-1 truncate text-left">{activeDateSourceLabel}</span>
                  <ChevronDown
                    className={`ml-[8px] h-[14px] w-[14px] shrink-0 text-folk-secondary transition-transform ${isDateSourceDropdownOpen ? "rotate-180" : ""}`}
                    strokeWidth={1.5}
                  />
                </button>
                <FixedSelectDropdown
                  isOpen={isDateSourceDropdownOpen}
                  anchorRef={dateSourceDropdownRef}
                  onClose={() => setIsDateSourceDropdownOpen(false)}
                  estimatedHeight={dateSourceOptions.length * 52 + 8}
                  minWidth={280}
                >
                  {dateSourceOptions.map((option) => {
                    const isSelected = dateSource === option.value
                    return (
                      <button
                        key={option.value}
                        type="button"
                        onClick={() => handleDateSourceChange(option.value)}
                        className={`flex w-full flex-col items-start px-[12px] py-[8px] text-left transition-colors hover:bg-folk-hover ${isSelected ? "bg-[var(--folk-border-subtle)]" : ""}`}
                        tabIndex={0}
                      >
                        <span className="text-[12px] font-medium text-folk-text">{option.label}</span>
                        {option.description && (
                          <span className="mt-[2px] text-[11px] text-folk-secondary">{option.description}</span>
                        )}
                      </button>
                    )
                  })}
                </FixedSelectDropdown>
              </div>
            </div>
          )}

          <div>
            <label className="mb-[4px] block text-[12px] font-medium text-folk-secondary">Start date *</label>
            <div className="relative">
              <button
                ref={startDateRef}
                type="button"
                onClick={() => {
                  onSetBudgetStartPickerOpen(!budgetStartPickerOpen)
                  onSetBudgetEndPickerOpen(false)
                }}
                className="flex h-[36px] w-full items-center rounded-none border border-folk-border bg-folk-page px-[12px] text-[13px] font-medium text-folk-text transition-colors hover:border-[#ccc]"
                tabIndex={0}
              >
                {budgetStartDate ? (
                  <span>{formatPickerDate(budgetStartDate)}</span>
                ) : (
                  <span className="text-folk-placeholder">Select date</span>
                )}
              </button>
              <FixedDatePickerDropdown
                isOpen={budgetStartPickerOpen}
                anchorRef={startDateRef}
                value={budgetStartDate}
                onChange={handleManualStartDateChange}
                onClose={() => onSetBudgetStartPickerOpen(false)}
              />
            </div>
          </div>

          <div>
            <label className="mb-[4px] block text-[12px] font-medium text-folk-secondary">End date *</label>
            <div className="relative">
              <button
                ref={endDateRef}
                type="button"
                onClick={() => {
                  onSetBudgetEndPickerOpen(!budgetEndPickerOpen)
                  onSetBudgetStartPickerOpen(false)
                }}
                className="flex h-[36px] w-full items-center rounded-none border border-folk-border bg-folk-page px-[12px] text-[13px] font-medium text-folk-text transition-colors hover:border-[#ccc]"
                tabIndex={0}
              >
                {budgetEndDate ? (
                  <span>{formatPickerDate(budgetEndDate)}</span>
                ) : (
                  <span className="text-folk-placeholder">Select date</span>
                )}
              </button>
              <FixedDatePickerDropdown
                isOpen={budgetEndPickerOpen}
                anchorRef={endDateRef}
                value={budgetEndDate}
                onChange={handleManualEndDateChange}
                onClose={() => onSetBudgetEndPickerOpen(false)}
              />
            </div>
          </div>

          {releasePeriods.length > 0 && (
            <div>
              <div className="mb-[6px] flex items-center justify-between">
                <label className="text-[12px] font-medium text-folk-secondary">Release schedule</label>
                <button
                  type="button"
                  onClick={handleResetSchedule}
                  className="flex items-center gap-[4px] text-[11px] font-medium text-folk-secondary transition-colors hover:text-folk-text"
                  tabIndex={0}
                >
                  <RotateCcw className="h-[11px] w-[11px]" strokeWidth={1.5} />
                  Reset schedule
                </button>
              </div>
              <div className="overflow-hidden rounded-none border border-[#e8e8e8]">
                {releasePeriods.map((period) => (
                  <div
                    key={period.id}
                    className="flex items-center gap-[8px] border-b border-folk-border-subtle px-[12px] py-[8px] last:border-b-0"
                  >
                    <div className="min-w-0 flex-1">
                      <p className="text-[12px] font-medium text-folk-text">Period {period.periodNumber}</p>
                      <p className="mt-[2px] text-[11px] text-folk-secondary">
                        {formatPickerDate(period.startDate)} – {formatPickerDate(period.endDate)}
                      </p>
                    </div>
                    <div className="relative w-[100px] shrink-0">
                      <span className="pointer-events-none absolute left-[8px] top-1/2 -translate-y-1/2 text-[11px] text-folk-secondary">$</span>
                      <input
                        type="text"
                        inputMode="decimal"
                        value={period.allocatedAmount > 0 ? formatNumberDisplay(period.allocatedAmount) : ""}
                        onChange={(e) => handlePeriodAmountChange(period.id, formatNumberInput(e.target.value))}
                        className="h-[30px] w-full rounded-none border border-folk-border bg-folk-surface pl-[18px] pr-[8px] text-[12px] font-medium text-folk-text outline-none focus:border-[#a3c4f3]"
                        aria-label={`Period ${period.periodNumber} amount`}
                      />
                    </div>
                  </div>
                ))}
              </div>
              <div className="mt-[6px] flex items-center justify-between text-[11px]">
                <span className="text-folk-secondary">
                  Total: {formatCurrency(periodsTotal)} / {formatCurrency(parsedAmount)}
                </span>
                {fundingComponent && (
                  <span className="text-folk-secondary">{NDIS_FUNDING_COMPONENT_LABELS[fundingComponent]}</span>
                )}
              </div>
              {scheduleWarning && (
                <p className="mt-[6px] rounded-none bg-amber-50 px-[10px] py-[6px] text-[11px] font-medium text-amber-700">
                  {scheduleWarning}
                </p>
              )}
            </div>
          )}
        </div>
      </div>

      <div className="flex shrink-0 items-center justify-between gap-[8px] border-t border-folk-border-subtle px-[24px] py-[12px]">
        {isEditing && onDelete && editingBudgetId ? (
          <DeleteActionsMenu
            onDelete={() => onDelete(editingBudgetId)}
            itemName={budgetName.trim() || "Untitled budget"}
            confirmTitle="Delete budget"
            confirmDescription={`This will permanently delete the budget "${budgetName.trim() || "Untitled budget"}" and any linked spending plans. This action cannot be undone.`}
            menuPlacement="top"
          />
        ) : (
          <span />
        )}
        <div className="flex items-center gap-[8px]">
        <button
          type="button"
          onClick={onClose}
          className="rounded-none border border-folk-border bg-folk-surface px-[12px] py-[6px] text-[12px] font-medium text-folk-text transition-colors hover:bg-folk-hover"
          tabIndex={0}
        >
          Cancel
        </button>
        <button
          type="button"
          onClick={onSave}
          disabled={!canSave}
          className="primary-btn px-[12px] py-[6px] text-[12px] font-medium transition-colors disabled:opacity-50"
          tabIndex={0}
        >
          {isEditing ? "Save changes" : "Create budget"}
        </button>
        </div>
      </div>
    </>
  )
}
