import {
  AlignLeft,
  Calendar,
  CalendarClock,
  CheckSquare,
  ChevronDownSquare,
  Clock,
  FileSignature,
  FileText,
  Hash,
  Heading,
  Link as LinkIcon,
  ListChecks,
  Mail,
  Minus,
  Phone,
  SlidersHorizontal,
  Star,
  Tag,
  Type,
  Upload,
  User,
  Users,
} from "lucide-react"
import type { ComponentType } from "react"
import type { FormFieldType } from "@/lib/form-definitions"

export const FIELD_ICONS: Record<FormFieldType, ComponentType<{ className?: string; strokeWidth?: number }>> = {
  "short-text": Type,
  "long-text": AlignLeft,
  "rich-text": FileText,
  email: Mail,
  phone: Phone,
  url: LinkIcon,
  number: Hash,
  tags: Tag,
  dropdown: ChevronDownSquare,
  "single-select": CheckSquare,
  "multi-select": ListChecks,
  checkbox: CheckSquare,
  "staff-select": Users,
  "client-select": User,
  "linear-scale": SlidersHorizontal,
  rating: Star,
  date: Calendar,
  time: Clock,
  datetime: CalendarClock,
  heading: Heading,
  paragraph: AlignLeft,
  divider: Minus,
  "file-upload": Upload,
  signature: FileSignature,
}
